### ISSUE TITLE
Confirm old bug reports

### ISSUE THREAD

**Issue by AndrewEdmonds11** [Mu2e/TrkAna#162]
We have a number of old open issues that are bug reports. This issue is to go through and work out which are still valid and need to be solved

**Comment by sam-grant** [comment]
I can take a look at this.

**Comment by sam-grant** [comment]
I looked through a few old bug reports and tried to establish if they are still a problem. See my comments on each issue for more details! 

[Issue/47](https://github.com/Mu2e/TrkAna/issues/47): I can produce a similar error using the latest TrkAna, so I think this is still a problem.   
[Issue/91](https://github.com/Mu2e/TrkAna/issues/91): I can reproduce the error if I use `TrkQualFilter`, but this is being phased out so I think this issue can be closed. 
[Issue/167](https://github.com/Mu2e/TrkAna/issues/167): This issue is not really a bug but a result of the way local tracker variables are stored in TrkAna, we discussed some different ways to handle this using uproot in the comments. 
[Issue/168](https://github.com/Mu2e/TrkAna/issues/168): This is still a problem, but I think it may be a limitation of ROOT rather than a bug in TrkAna (although I'm not sure what causes it).

**Comment by AndrewEdmonds11** [comment]
Thanks, Sam! I will follow up on next steps for these in the issues themselves

**Comment by AndrewEdmonds11** [comment]
I've looked at a few more:

Issue #21: I couldn't recreate the bug but we should check that we can run on data-only files (i.e. with no MC information)
Issue #90: this was already done and so has been closed
Issue #93: the bestcrv branch has been removed so this is no longer an issue

**Comment by AndrewEdmonds11** [comment]
I don't see any more old issues to confirm so this is done
